<JLblTxtBtn@BoxLayout>:
    l_text: '0default'
    b_text: '2default'
    orientation: 'horizontal'
    Label:
        text: root.l_text
    TextInput:
        text: ''
    Button:
        text: root.b_text
            
<MyLayout>:  
    orientation: 'vertical'
    
    JLblTxtBtn:   
        l_text: 'A'
        b_text: 'C'
        
        
    JLblTxtBtn:   
        l_text: 'G'
        b_text: 'I'